# Generated by Django 4.2.20 on 2025-03-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='time_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
